### PR TITLE
[ASSIST-765]: Spike: Resolve issue with implicit uuid casting (30 Minutes)

### PR DESCRIPTION
**Pull request by Orrison**
### Ticket(s) or GitHub Issue

- https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/765/

### Technical Description

Switches Prospects back to uuid for the primary key. I could not reproduce an issue with the filter even after switching prospects back to a UUID column.
The filter works, and I get back the results I would expect.

If y'all have any specific details so I can reproduce an error to debug, let me know.

### Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue)

### Any deployment steps required?

A deployment step could be a command that needs to be executed or an ENV key that needs to be added, for example.

- [x] No

_______________________________________________

## Before contributing and submitting this PR, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/canyongbs/assistbycanyongbs/blob/main/README.md#contributing).
* [x] Title the PR with the ticket/issue number and a short description of the changes made. Or if no ticket/issue exists, title the PR with a short description of the changes made
* [x] Linked a relevant ticket or issue or describe the issue/feature which this PR resolves/implements.
* [x] Resolved all conflicts, if any.
* [x] Rebased your branch PR on top of the latest upstream `develop` branch.

### CODE REVIEW

**Comment by danharrin** [comment]
@mxm1070 maybe you could try testing that filter locally with this change? I'm sure that the bug still exists, we just aren't reproducing it properly

**Comment by Orrison** [comment]
@mxm1070 if you can please test with this branch locally and let me know if you can still reproduce this issue. And if so please provide me with some steps to do so.
I have tried all the suggestions so far and have not had any errors.

**Comment by dgoetzit** [comment]
@Orrison I am able to reproduce this locally. 

Steps to reproduce:
1. Freshly seeded database on the working branch
2. View any prospect record
3. Navigate to "Care Team" navigation item, select "Add to Care Team"
4. Search for User

**Comment by Orrison** [comment]
@danharrin and @mxm1070, this should now be fixed with the most recent push.

**Review by dgoetzit — APPROVED** [review]

**Pull request merged**
