### PR TITLE
[ASSIST-491]: Setup Automated formatting and linting in Github Actions 

### PR DESCRIPTION
**Pull request by Orrison**
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/491/

### CODE REVIEW

**Review by dgoetzit — DISMISSED** [review]

**Comment by danharrin** [comment]
I think there is a way to integrate this tool with Pint for formatting within directives, is that also done in this PR?

**Comment by Orrison** [comment]
> I think there is a way to integrate this tool with Pint for formatting within directives, is that also done in this PR?

I am not sure what you mean. Like being about to decide which files are targeted by formatting? That is configured with our PHP_CS_Fixer config and our Prettier config.

Isn't Pint just a wrapper for PHP_CS_Fixer with less flexibility?

**Comment by danharrin** [comment]
Pint is natively integrated with the formatter - https://github.com/Stillat/blade-parser-typescript/tree/main/formatter#configuring-laravel-pint

Yeah it's a wrapper around CS Fixer, but I don't think blade-parser-typescript has support for that

**Comment by Orrison** [comment]
> Pint is natively integrated with the formatter - https://github.com/Stillat/blade-parser-typescript/tree/main/formatter#configuring-laravel-pint
> 
> Yeah it's a wrapper around CS Fixer, but I don't think blade-parser-typescript has support for that

@danharrin this ticket does not encapsulate changing the blade formatter yet. That is in a separate ticket. We could look into the changes you are suggesting then?

**Comment by danharrin** [comment]
Oh, well I would suggest using that formatter, it handles everything much better.

My fault for not reading the scope of the ticket, I thought that was part of the task. Ignore me if you want to just focus on the CI.

**Comment by Orrison** [comment]
> Oh, well I would suggest using that formatter, it handles everything much better.
> 
> My fault for not reading the scope of the ticket, I thought that was part of the task. Ignore me if you want to just focus on the CI.

Yeah for now this is just setting up the formatting we have existing with PHP_CS_FIXER and that Prettier blade extension we are using.
There is a different ticket to assess changing to the one you suggested.

If you can review this process and approve @danharrin that would be great!

**Review by danharrin — APPROVED** [review]

**Pull request merged**
